### ISSUE TITLE
[Question] Use of FastNoiseSIMD

### ISSUE THREAD

**Issue by Zbluu** [midgen/UnrealFastNoise#14]
This is not a real issue, but more a question.

I'd like to know if you've succeeded to use the [FastNoiseSIMD](https://github.com/Auburns/FastNoiseSIMD) library instead of the simple [FastNoise](https://github.com/Auburns/FastNoise) library.
I saw that you said on the forum you'd try to implement it in your plugin, what about this ?
I also saw that there is a branch of this plugin that use the FastNoiseSIMD library, can we use it ?
Is there any reason you gave up the idea?

I ask because I myself have worked on this library but I encounter mysterious problems (see [here](https://answers.unrealengine.com/questions/881233/cant-compile-after-add-empty-cpp-file.html)).
So it would be great if I can use your plugin with FastNoiseSIMD library performances 😄

**Comment by midgen** [comment]
It's not straightforward to implement the SIMD version explicitly in a general purpose plugin like this, it would require a large amount of rework. Not likely I will get a chance to implement I'm afraid.
