### ISSUE TITLE
How do I reference a UFastNoise object?

### ISSUE THREAD

**Issue by devonak** [midgen/UnrealFastNoise#4]
I keep getting the compile error on the plugin `error LNK2019: unresolved external symbol "private: static class UClass * __cdecl UFastNoise::GetPrivateStaticClass(wchar_t const *)" (?GetPrivateStaticClass@UFastNoise@@CAPEAVUClass@@PEB_W@Z) referenced in function "public: class UFastNoise * __cdecl UObject::CreateDefaultSubobject<class UFastNoise>(class FName,bool)" (??$CreateDefaultSubobject@VUFastNoise@@@UObject@@QEAAPEAVUFastNoise@@VFName@@_N@Z)`

I've added public UnrealFastNoisePlugin to the build.cs and included FastNoise/FastNoise.h yet I can't seem to create a reference to UFastNoise\* myNoiseOBJ.  myNoiseOBJ= CreateDefaultSubobject<UFastNoise>(TEXT("Noise"));

I'm on 4.13

**Comment by devonak** [comment]
I'm not sure if I'm using it wrong or not because I'm new to programming but I was never able to create aa pointer to UFastNoise\* or UUFNNoiseGenerator\* until I went through all the header files and added UNREALFASTNOISEPLUGIN_API to the UCLASS macro.  Once I did that I could successfully create a reference to the noise generator and derive my noise from it.

**Comment by midgen** [comment]
Thanks, I've pushed that change!
