### ISSUE TITLE
Assertion failed: m_cellularNoseLookup

### ISSUE THREAD

**Issue by HeadBoopGames** [midgen/UnrealFastNoise#7]
This is probably a bug related to the new CG_World branch. But I posted it anyways. :)

LoginId:04124014408025726c6f6bad0be6fdff
EpicAccountId:b4198a5ffd5c41b782e153304bd477f2

Assertion failed: m_cellularNoiseLookup [File:P:\FrozenRune\PlanetRaiders\PlanetRaiders\Plugins\UnrealFastNoise\Source\UnrealFastNoisePlugin\Private\FastNoise\FastNoise.cpp] [Line: 1498] 

KERNELBASE
UE4Editor_Core
UE4Editor_Core
UE4Editor_Core
UE4Editor_UnrealFastNoisePlugin!UFastNoise::SingleCellular() [p:\frozenrune\planetraiders\planetraiders\plugins\unrealfastnoise\source\unrealfastnoiseplugin\private\fastnoise\fastnoise.cpp:1501]
UE4Editor_UnrealFastNoisePlugin!UUFNScaleBiasModule::GetNoise3D() [p:\frozenrune\planetraiders\planetraiders\plugins\unrealfastnoise\source\unrealfastnoiseplugin\private\ufnscalebiasmodule.cpp:17]
UE4Editor_UnrealFastNoisePlugin!UUFNBlendModule::GetNoise3D() [p:\frozenrune\planetraiders\planetraiders\plugins\unrealfastnoise\source\unrealfastnoiseplugin\private\ufnblendmodule.cpp:25]
UE4Editor_CashGen!FCGWorldGeneratorWorker::SubDivideGeometry() [p:\frozenrune\planetraiders\planetraiders\plugins\cashgenue-cg_world\source\cashgen\private\cgworldgeneratorworker.cpp:14]
UE4Editor_CashGen!FCGWorldGeneratorWorker::SubDivideGeometry() [p:\frozenrune\planetraiders\planetraiders\plugins\cashgenue-cg_world\source\cashgen\private\cgworldgeneratorworker.cpp:29]
UE4Editor_CashGen!FCGWorldGeneratorWorker::SubDivideGeometry() [p:\frozenrune\planetraiders\planetraiders\plugins\cashgenue-cg_world\source\cashgen\private\cgworldgeneratorworker.cpp:29]
UE4Editor_CashGen!FCGWorldGeneratorWorker::SubDivideGeometry() [p:\frozenrune\planetraiders\planetraiders\plugins\cashgenue-cg_world\source\cashgen\private\cgworldgeneratorworker.cpp:29]
UE4Editor_CashGen!FCGWorldGeneratorWorker::SubDivideGeometry() [p:\frozenrune\planetraiders\planetraiders\plugins\cashgenue-cg_world\source\cashgen\private\cgworldgeneratorworker.cpp:29]
UE4Editor_CashGen!FCGWorldGeneratorWorker::SubDivideGeometry() [p:\frozenrune\planetraiders\planetraiders\plugins\cashgenue-cg_world\source\cashgen\private\cgworldgeneratorworker.cpp:29]
UE4Editor_CashGen!FCGWorldGeneratorWorker::SubDivideGeometry() [p:\frozenrune\planetraiders\planetraiders\plugins\cashgenue-cg_world\source\cashgen\private\cgworldgeneratorworker.cpp:29]
UE4Editor_CashGen!FCGWorldGeneratorWorker::SubDivideGeometry() [p:\frozenrune\planetraiders\planetraiders\plugins\cashgenue-cg_world\source\cashgen\private\cgworldgeneratorworker.cpp:29]
UE4Editor_CashGen!FCGWorldGeneratorWorker::Run() [p:\frozenrune\planetraiders\planetraiders\plugins\cashgenue-cg_world\source\cashgen\private\cgworldgeneratorworker.cpp:67]
UE4Editor_Core
UE4Editor_Core
kernel32
ntdll

**Comment by midgen** [comment]
Tidying up, very old issue and the offending code is no longer in the repo
