### ISSUE TITLE
Can't enable it in a 4.17.1 project

### ISSUE THREAD

**Issue by victorbstan** [midgen/UnrealFastNoise#9]

**Comment by victorbstan** [comment]
![2017-08-25 14_20_21-epic games launcher fast noise plugin issues](https://user-images.githubusercontent.com/315297/29727274-2981fdb6-89a1-11e7-8f96-8234620a7ec0.png)

**Comment by Dealman** [comment]
If your project is a BP project, you'll want to add a C++ class file, this will generate the necessary source files to compile code. Once this is done, restart the editor and click no and then when prompted if you want to try and rebuild it from source - click yes.

I can confirm that it works.

**Comment by midgen** [comment]
Yep sorry you'll need to compile the plugin yourself. Dealman's instructions will work.
